# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: ["xyz"]

jobs:
  SetupAndCompile:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    
    - name: setup with Maven
      run: mvn -B clean --file pom.xml
    - name: compile with Maven
      run: mvn -B compile --file pom.xml
  StaticAnalysis:
    runs-on: ubuntu-latest
    needs: SetupAndCompile
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location
    - name: SonarCloud scan
      env:
        github-token: ${{ secrets.GATOKEN }}
        sonar-token: ${{ secrets.SATOKEN }}
      run: mvn -X verify sonar:sonar

  UnitTesting:
    runs-on: ubuntu-latest
    needs: SetupAndCompile
    steps:
      - run: echo should run unit test
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        run: mvn -B test --file pom.xml
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'target/surefire-reports/*.xml'
  CodeCoverage:
    runs-on: ubuntu-latest
    needs: UnitTesting
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and Run Tests
        run: mvn -X org.jacoco:jacoco-maven-plugin:report
      
    
    

   
